### ISSUE TITLE
fallback to MONGO_URL env var before raising error

### ISSUE THREAD

**Issue by paulwalker** [okv/east-mongo#3]
the current implementation means a separate configuration file per environment, which is kinda anti 12 factor, blah, blah...

**Comment by okv** [comment]
east provides `--url` and other options to specify settings via command line

**Comment by ksmithut** [comment]
You could also create an `.eastrc` file and give it:
```js
'use strict'

module.exports = {
  adapter: 'east-mongo',
  url: process.env.MONGO_URL,
}
```

**Comment by okv** [comment]
@ksmithut true, that's also an option, thanks. No reply, I'm closing it.
