### ISSUE TITLE
mongodb native api change

### ISSUE THREAD

**Issue by henryoswald** [okv/east-mongo#5]
The api for mongodb native has changed blowing up east-mongo. Need to either lock down the version of mongodb or upgrade the api usage. I will create a quick pr for the lock down option

error:

`the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize]
target migrations:`

**Comment by okv** [comment]
Lock down accepted #6
But it's strange behavior of mongodb driver - with mongodb 2.2.34 I still get that warning but all seems to work fine:

```sh
east rollback
the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,ciphers,ecdhCurve,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,keepAliveInitialDelay,checkServerIdentity,validateOptions,appname,auth]
target migrations:
	1_apples
rollback `1_apples`
migration successfully rolled back

``` 

with mongodb 3.0.2 it blows up:

```sh
east migrate
the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize]
/home/oleg/tmp/east/node_modules/mongodb/lib/mongo_client.js:814
          throw err;
          ^

TypeError: db.collection is not a function
    at /home/oleg/tmp/east/node_modules/east-mongo/lib/adapter.js:26:25
    at /home/oleg/tmp/east/node_modules/mongodb/lib/utils.js:404:72
    at /home/oleg/tmp/east/node_modules/mongodb/lib/mongo_client.js:271:5
    at connectCallback (/home/oleg/tmp/east/node_modules/mongodb/lib/mongo_client.js:950:5)
    at /home/oleg/tmp/east/node_modules/mongodb/lib/mongo_client.js:811:11
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
```

**Comment by okv** [comment]
I don't really understand what that warning is telling)
@henryoswald do you know more about that? Which api was changed?

**Comment by henryoswald** [comment]
mongoclient.connect doesn't return the db instance any more
https://github.com/okv/east-mongo/blob/master/lib/adapter.js#L23

instead it returns the 'client', so you need to run `db = client.db(dbName)`

https://github.com/mongodb/node-mongodb-native#connect-to-mongodb

it should look something like this:

	Adapter.prototype.connect = function(callback) {
		var self = this;
		MongoClient.connect(
			self.params.url,
			self.params.options || {},
			function(err, client) {
				if (err) {callback(err); return;}
				if (!client){callback("connection to mongodb failed")}
				self.db = client.db(self.params.dbName);
				self.collection = self.db.collection('_migrations');
				callback(null, {
					db: self.db,
					dropIndexIfExists: self.helpers.dropIndexIfExists
				});
			}
		);
	};

**Comment by okv** [comment]
ok, thanks, I'll take a look at that.

But seems that api changes aren't related to that warning:

> the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize]

**Comment by okv** [comment]
support for driver v3 added since east-mongo@0.3.6
